<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Nulltrap</AssemblyName>
    <RootNamespace>Nulltrap.App</RootNamespace>
    <ApplicationIcon>Nulltrap.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <PropertyGroup>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Drawing" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nulltrap.Core\Nulltrap.Core.csproj" />
    <ProjectReference Include="..\Nulltrap.Platform.Windows\Nulltrap.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Nulltrap.ico" />
    <Resource Include="Nulltrap.png" />
    <Resource Include="NulltrapSmall.png" />
  </ItemGroup>

</Project>
