<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nulltrap.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nulltrap.Platform.Abstractions\Nulltrap.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\Nulltrap.Plugins.Sdk\Nulltrap.Plugins.Sdk.csproj" />
  </ItemGroup>

</Project>
